### PR TITLE
bump ram to 4gb for ipa tests

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
[citest]

**Comment by seocam** [comment]
Since we didn't merge #23 (which bumped from 2gb to 3gb) I can rebase with 4gb there.
Do we actually need the 4gb?

**Comment by amore17** [comment]
> Since we didn't merge #23 (which bumped from 2gb to 3gb) I can rebase with 4gb there.
> Do we actually need the 4gb?

I have also tested with m: 4072
As part of https://github.com/linux-system-roles/certificate/pull/39/commits/7eba505731e8794d6157d425b9cac0d06c70d33c#diff-043f258a8145f15d0c6300c6f8918e7bR3
Its failing with m: 4072.

**Comment by seocam** [comment]
#23 updated with 4gb of ram.

**Pull request closed without merging**
