### PR TITLE
docs(changelog): version 1.3.4 [citest skip]

### PR DESCRIPTION
**Pull request by spetrosi**
Update changelog and .README.html for version 1.3.4

Signed-off-by: Sergei Petrosian <spetrosi@redhat.com>

### CODE REVIEW

**Comment by richm** [comment]
> Only now I saw that ansible-lint was bumped to version 24. In ansible-freeipa we found that this version is "hit and miss" and was unstable. Is it required to use version 24 right now?

We generally use whatever version Galaxy and Automation Hub use for gating, and right now that is 24.  What issues are you seeing?

**Comment by rjeffman** [comment]
There were lots of failures on it creating the virtual environment.

We also (try to) use the same version as Galaxy and Automation Hub, and if it is using 24, I'll update it there.

**Review by rjeffman — APPROVED** [review]
lgtm.

**Comment by richm** [comment]
> There were lots of failures on it creating the virtual environment.

ansible-lint, or ansible-test?

> 
> We also (try to) use the same version as Galaxy and Automation Hub, and if it is using 24, I'll update it there.

**Comment by rjeffman** [comment]
ok... I found out the issue with ansible-lint, and it was on ansible-freeipa. It is fixed now.

**Review by richm — APPROVED** [review]

**Pull request merged**
