### PR TITLE
Add idempotence tests

### PR DESCRIPTION
**Pull request by seocam**

### CODE REVIEW

**Comment by richm** [comment]
@i386x here is an alternate way of doing idempotency/check mode testing via an ansible module

**Comment by jharuda** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
[citest pending]

**Comment by richm** [comment]
closing due to inactivity

**Pull request closed without merging**
