### PR TITLE
use new tox-lsr plugin

### PR DESCRIPTION
**Pull request by richm**

### CODE REVIEW

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest pending]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest bad]

**Comment by nhosoi** [comment]
[citest]

**Comment by nhosoi** [comment]
[citest]

**Comment by nhosoi** [comment]
[citest]

**Comment by richm** [comment]
PR is ready - switched to use the tox-lsr 1.0.0 release

**Review by rjeffman — APPROVED** [review]
lgtm.

**Comment by richm** [comment]
> lgtm.
> 
> But there is a failure with Python 3.6. Looks like molecule is failing to update packages with pip.

Yes.  There are more changes coming:
* drop centos6 from molecule
* drop ansible 2.7 from molecule
* add centos8 to molecule
* drop linting from molecule and instead use yamllint and ansible-lint from tox

**Pull request merged**
