### PR TITLE
support jinja 2.7

### PR DESCRIPTION
**Pull request by richm**
This is a WIP to test support for ansible-2.8/jinja 2.7

### CODE REVIEW

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
Note: rhel-x failures are due to https://pagure.io/freeipa/issue/8617

**Comment by nhosoi** [comment]
Reviewing the commits, lgtm.
For CI, once linux-system-roles-test/rhel-7 passes, we could say this PR is ready to merge?

**Comment by richm** [comment]
> Never mind. This platform rhel-7/ansible-2.8 already covers jinja 2.7, right?

Right - jinja 2.7 is covered by the `*/ansible-2.8` tests.  Also note that the `rhel-x` failures are due to a bug in ipa which has been fixed in the latest rhel-x images (but there hasn't been another snapshot release so we're stuck with the old image with the bug for now).

**Comment by pcahyna** [comment]
> Right - jinja 2.7 is covered by the `*/ansible-2.8` tests. Also note that the `rhel-x` failures are due to a bug in ipa which has been fixed in the latest rhel-x images (but there hasn't been another snapshot release so we're stuck with the old image with the bug for now).

@amore17 this information may be of interest to you - @richm do you know what package update has fixed it?

**Comment by richm** [comment]
> > Right - jinja 2.7 is covered by the `*/ansible-2.8` tests. Also note that the `rhel-x` failures are due to a bug in ipa which has been fixed in the latest rhel-x images (but there hasn't been another snapshot release so we're stuck with the old image with the bug for now).
> 
> @amore17 this information may be of interest to you - @richm do you know what package update has fixed it?

freeipa 4.9.0-1.el8

**Comment by richm** [comment]
ok to merge?

**Review by nhosoi — APPROVED** [review]
lgtm

**Pull request merged**
