### PR TITLE
ansible-lint 6.x fixes

### PR DESCRIPTION
**Pull request by richm**
Use `true`/`false` instead of `yes`/`no`
Fix spacing in braces/brackets
All tasks must be named
Documents should begin with `---`
Other cleanup

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Review by rjeffman — APPROVED** [review]
lgtm.

@richm what was failing due to the use of "yes/no"? IIRC, ansible-freeipa pass ansible-test with "yes/no".

**Comment by richm** [comment]
> lgtm.
> 
> @richm what was failing due to the use of "yes/no"? IIRC, ansible-freeipa pass ansible-test with "yes/no".

https://ansible-lint.readthedocs.io/rules/yaml/ - `yaml[truthy]` - see also https://github.com/redhat-cop/automation-good-practices/tree/main/coding_style#yaml-and-jinja2-syntax `Use true and false for boolean values in playbooks`

Not sure why you don't see this in ansible-freeipa - perhaps you are suppressing it in .ansible-lint or elsewhere?

**Comment by richm** [comment]
[citest]

**Comment by rjeffman** [comment]
> > lgtm.
> > @richm what was failing due to the use of "yes/no"? IIRC, ansible-freeipa pass ansible-test with "yes/no".
> 
> https://ansible-lint.readthedocs.io/rules/yaml/ - `yaml[truthy]` - see also https://github.com/redhat-cop/automation-good-practices/tree/main/coding_style#yaml-and-jinja2-syntax `Use true and false for boolean values in playbooks`
> 
> Not sure why you don't see this in ansible-freeipa - perhaps you are suppressing it in .ansible-lint or .yamllint.yml or elsewhere?

Found it. On `.yamllint` we have:
```yaml
  truthy:
    allowed-values: ["yes", "no", "true", "false", "True", "False"]
```

Thank you for the pointers.

**Pull request merged**
