### PR TITLE
Add certificate profile

### PR DESCRIPTION
**Pull request by ooraini**
Notes:
Changing the profile will not delete and re-issue the certificate.
I'm not sure how would I write a test with the self-signed provider. I have tested it with IPA and it works as expected.

### CODE REVIEW

**Comment by richm** [comment]
[citest]

**Comment by richm** [comment]
please rebase on top of latest master branch

**Comment by richm** [comment]
> Notes: Changing the profile will not delete and re-issue the certificate.

That sounds like the right behavior.

> I'm not sure how would I write a test with the self-signed provider.

It sounds like this feature isn't applicable to self-signed provider?

> I have tested it with IPA and it works as expected.

There is a test for ipa - https://github.com/linux-system-roles/certificate/blob/master/tests/tests_basic_ipa.yml#L13 - can you add a `profile` to one of these requests?

**Comment by richm** [comment]
[citest commit:b7d1b659eacf1ba2b014c138fb1a161fe283529d]

**Comment by ooraini** [comment]
This is disappointing. I will try to get things running locally and push again. Apologies.

**Comment by richm** [comment]
> This is disappointing. I will try to get things running locally and push again. Apologies.

Looks like your ide/editor is not putting a newline at EOF?

**Comment by richm** [comment]
https://linux-system-roles.github.io/contribute.html - so you can use `tox -e yamllint` to check - just be aware that if you are using fedora, you will need to install tox using pip - `pip install tox --user` - then install the `tox-lsr` plugin - because the Fedora RPM tox package does not allow user plugins

the contribute page also has instructions about how to run tests locally using qemu/kvm

**Comment by ooraini** [comment]
[citest commit:fbabc95a3771b1d3698970d130e36f20a83313a0]

**Comment by ooraini** [comment]
Hi @richm,

The last CI failure was due to RHEL/CentOS 7 not outputting the profile in `getcert list`. The new test is quite brittle. I'm think that we might be better off without it. What do you think?

**Comment by richm** [comment]
> Hi @richm,
> 
> The last CI failure was due to RHEL/CentOS 7 not outputting the profile in `getcert list`. The new test is quite brittle. I think that we might be better off without it. What do you think?

Can the test be made less brittle?  We need some way to test this functionality (in addition, the test serves as a form of documentation for end users who may be trying to use this feature, and want to see a working example).

If there really is no way to test this functionality in an automated way with our current test framework, then we will need some detailed documentation about how a QE team can verify and validate the feature.

**Comment by richm** [comment]
[citest commit:8b9c5868eb3199b188c5b7814e3f4df0165d8455]

**Comment by ooraini** [comment]
@richm I think this ready now. Not sure what is why the CI is still pending.

**Comment by richm** [comment]
> @richm I think this ready now.

yeah - lgtm - @rjeffman 

> Not sure what is why the CI is still pending.

fixed

**Comment by richm** [comment]
please rebase the PR on top of the latest master branch

**Comment by richm** [comment]
please rebase the PR on top of the latest master branch

**Comment by ooraini** [comment]
@richm rebased.

**Comment by rjeffman** [comment]
@ooraini and @richm, I'll be running a few tests against this PR today and tomorrow. On a first look, it looks good.

**Comment by richm** [comment]
[citest commit:d55578fe212cbb03c1edfbbf391459d37ff2f4f6]

**Comment by richm** [comment]
ping

**Comment by richm** [comment]
closing due to inactivity

**Pull request closed without merging**
