### PR TITLE
sync with latest template, including shellcheck

### PR DESCRIPTION
**Pull request by richm**
sync with latest template, including shellcheck
fix issues found by shellcheck

### CODE REVIEW

**Comment by richm** [comment]
@seocam I'm getting this error on fedora 31:
```
TASK [ipaserver : Install - Ensure that IPA server packages are installed] *****
task path: /tmp/freeipa-repo/roles/ipaserver/tasks/install.yml:5
fatal: [/cache/Fedora-Cloud-Base-31-1.9.x86_64.qcow2]: FAILED! => {"changed": false, "failures": [], "msg": "Unknown Error occured: Transaction check error:\n  file /usr/share/man/man5/idmapd.conf.5.gz from install of nfs-utils-1:2.5.1-0.fc31.x86_64 conflicts with file from package libnfsidmap-1:2.4.1-1.rc1.fc31.x86_64\n", "rc": 1, "results": []}
```
known issue?

**Comment by richm** [comment]
[citest failing]

**Comment by richm** [comment]
[citest bad]

**Comment by rjeffman** [comment]
I'm not aware of that issue.

**Pull request merged**
