### PR TITLE
Add test using ipa as CA

### PR DESCRIPTION
**Pull request by amore17**

### CODE REVIEW

**Comment by amore17** [comment]
[citest bad]

**Comment by amore17** [comment]
[citest bad]

**Comment by amore17** [comment]
[citest bad]

**Comment by richm** [comment]
[citest bad]

**Comment by amore17** [comment]
[citest bad]

**Comment by amore17** [comment]
[citest bad]

**Comment by amore17** [comment]
[citest bad]

**Comment by richm** [comment]
[citest bad]

**Comment by richm** [comment]
[citest bad]

**Comment by seocam** [comment]
@amore17 can I close this PR?

**Comment by amore17** [comment]
> @amore17 can I close this PR?

Yes this is just to added foe debugging issue for memory failure.

**Pull request closed without merging**
