### PR TITLE
meta/main.yml: CI add support for all Fedora images

### PR DESCRIPTION
**Pull request by jharuda**
Signed-off-by: Jakub Haruda <jharuda@redhat.com>

### CODE REVIEW

**Review by richm — APPROVED** [review]
lgtm

**Review by rjeffman — APPROVED** [review]
lgtm

**Comment by richm** [comment]
Any objection to merging this PR?

**Comment by rjeffman** [comment]
Sorry, I was waiting for tests to finish and completely forgot about it.
Merged.

**Pull request merged**
